### ISSUE TITLE
Please create a useful README

### ISSUE THREAD

**Issue by rfay** [vinugawade/ddev-civicrm-cli-tools#1]
Thanks for your work on this!

Please put a useful README.md in there. The copy of the template doesn't help anybody to understand what the add-on is for or how to use it.

Thanks!

**Comment by vinugawade** [comment]
Thanks for your feedback, @rfay!

I’ve added the detailed `README.md` with the necessary information about the add-on’s purpose and usage. You can check the commit here: cf33235306c7d9b70173c76b8617ddd9f31c07dc

With this change, I am closing the issue. Please feel free to let me know if anything else needs to be updated.

**Comment by rfay** [comment]
Looks great! 🚀
